### ISSUE TITLE
new vesion  IDE cann't work!

### ISSUE THREAD

**Issue by helloworld8686** [1010Technologies/pxt-makerbit-ir-receiver#3]
https://makecode.microbit.org/#editor

**Comment by philipphenkel** [comment]
The event handling in MakeCode is currently buggy. Fortunately, the issue is fixed in the upcoming version (makecode.microbit.org Version:  3.1.1). A preview of that version is available at
https://makecode.microbit.org/beta

Here's a simple program that works in version 3.1.1:

```
makerbit.onIrButton(IrButton.Any, IrButtonAction.Pressed, function () {
    basic.showNumber(makerbit.pressedIrButton())
    basic.showString("R")
})


basic.showString("R")
makerbit.connectInfrared(DigitalPin.P0)
```

**Comment by philipphenkel** [comment]
Fixed. Micro:bit MakeCode 2020 was released some days ago.
