### ISSUE TITLE
Using alternative IR remotes

### ISSUE THREAD

**Issue by pdbperks** [1010Technologies/pxt-makerbit-ir-receiver#4]
Pillip,
'The extension should also work with other IR receivers and NEC compatible IR remotes.'
Do you have any plans for allowing easy integration of IrButton codes?
Or guidance for adapting IR codes? I have some experience with IR on Arduino and have used the Circuit Playgroud Express to send a range of codes hoping to simulate Up = 0x62, The hardware is functioning but I have had no success with the software so far.
David

**Comment by philipphenkel** [comment]
In the current version we ignore the address and thus accept all incoming NEC IR commands (0 - 255).
The following code snippet displays a received command. I recommend using a real remote control in the beginning to eliminate an issue at the sender side.

```
makerbit.connectIrReceiver(DigitalPin.P0)

basic.forever(function () {
    if (makerbit.wasAnyIrButtonPressed()) {
        basic.showNumber(makerbit.irButton())
    }
})

```

**Comment by pdbperks** [comment]
Dear Philipp,
Thank you very much for a prompt response.
I have tried your code snippit but without any success.
My IR sensor board has an LED indicator and this flashes when a controller key is pressed. Also, if I attach the sensor to pin 3, a sequence of lights on the micro:bit display flickers when a key is pressed. It is powered by 3v from the micro:bit. The hardware circuit would seem to be correct. I have indeed been able to achieve IR control using an alternative extension (https://makecode.microbit.org/pkg/tinkertanker/pxt-ir-receiver) and some acrobatic coding.
Your extension however, is better featured; so it is a frustration that I am making no progress. IR control of a micro:bit offers great potential; providing a large range of input buttons but using only a single IO pin.  

I have a range of IR handsets. They all seem to be NEC format.  Here is an example read from an Arduino Uno using IRrecvDump by Ken Shirriff.
Output:-
Decoded NEC: FF22DD (32 bits)
Raw (68): -3866 9000 -4450 600 -500 650 -500 600 -500 600 -550 600 -500 600 -500 650 -500 600 -500 650 -1600 600 -1600 650 -1600 600 -1600 650 -1600 600 -1600 650 -1600 600 -1600 600 -550 600 -500 600 -1650 600 -500 600 -500 650 -500 600 -1600 650 -500 600 -1600 650 -1600 600 -500 650 -1600 600 -1600 650 -1600 600 -500 650 -1600 600 
A code signal that would appear to equate with your value for left, as identified in infrared-receiver.ts
  //% block="◀"
  Left = 0x22,
  
I  have tried 2 micro:bit boards (Interface Version: 0253) with no success.  I remain mystified but I am learning a lot.
David

**Comment by philipphenkel** [comment]
Dear David, 
5 minutes ago I released a much improved version. 
This version works ok with my keyestudio remote control and perfect with my Yamaha sound system's remote control. 
I'm powering my Keyesstudio IR receiver with 5V (MakerBit boards offer both 3V and 5V). Another potential problem is using the wrong pin in the connectIrReceiver function.

Please have a look at the latest release 1.3.1 and let me know if that works for you.

**Comment by pdbperks** [comment]
Philipp,
How amusing. Since my last post, I had an idea that the problem might have been in the MakeCode app which I am running in Chrome. So I looked for an alternative and downloaded the win10 app, flashed a demo program and had instant success! Of course, when I return here to tell you of this great discovery, I find your post about the 1.3.1 upgrade. I am now back to the web app in Chrome and your extension is running as expected.  Blocks work for pressed and released instructions, which is just what I needed.  Now I can get back to work on my micro:bit midi project with added IR control.
Absolutely fantastic! Greatly appreciated.
David

**Comment by philipphenkel** [comment]
Nice! I'm glad it's working now. I would love to see/hear you project, once you are done 😄 

Just in case anyone else is reading this: I forgot to mention that the extension requires the Beta version of MakeCode at https://makecode.microbit.org/beta  In the next weeks they will turn Beta into the default version.
