### ISSUE TITLE
Microbit v2

### ISSUE THREAD

**Issue by Shirley725** [1010Technologies/pxt-makerbit-ir-receiver#5]
Hi, 

I was using microbit v1 and everything works perfectly, however, i just bought a new version which is microbit v2 and the remote no longer work. Is that any way to resolve the issue?

Thanks,
Shirley

**Comment by philipphenkel** [comment]
Thanks for reporting that. At the moment, we don't have a workaround available. 

We are collaborating with the MakeCode team to support both v1 and v2 for all our extensions and we will provide an update here once the IR receiver works on v2 as well.

**Comment by philipphenkel** [comment]
@Shirley725 Good news. The MakeCode team fixed the problem in the stable version https://makecode.microbit.org/stable and soon it will be available in the default editor as well.

**Comment by Shirley725** [comment]
Great! Thanks for your help!

**Comment by philipphenkel** [comment]
As of today, the stable version is the new default (live) version. Problem solved.

Fixed by https://github.com/microsoft/pxt-microbit/pull/3856
